Added bootstrap_.py that takes filename as argument along with LOA and year
prio-data/prediction_competition_2023 pull request #35
Opened 2023-10-16 09:49 UTC by nskazmi

2023-10-16 10:00 UTC, nskazmi commented
<img width="1390" alt="image" src="https://github.com/prio-data/prediction_competition_2023/assets/142994595/4193957f-0dc0-4407-9da4-3a5b85942ab6">

2023-10-16 10:01 UTC, nskazmi commented
this is how it works from terminal

2023-10-17 09:10 UTC, kvelleby requested changes
Thanks for this. Your code works, but I would like some refactoring, partially due to a moving target from my side. Sorry about that. See comments in the boostrap_.py module. Other than those comments, I also want a request containing only this file, without the ipython notebook. Thanks! :)

2023-10-17 09:10 UTC, kvelleby commented on bootstrap_.py
I was thinking you would be better off using the features data than the "actuals" files. Here is a short example of what I was thinking. It should then be saved to a Apache Hive kind of structure: i.e., benchmark_boostrap/pgm/year=2018/predictions.parquet ... and so on. The implementation now uses "the year before". One question is whether we should use the year before, but from Oct-Oct. E.g., for 2020, we draw from a pool of data from Oct 2018 to Oct 2019. The features data now contains a "month" column so you could select that (pac.field("year) > year-2, then subset the pandas file removing the months that should not be in the pool.

```
def global_bootstrap_benchmark(feature_folder, target, year) -> pd.DataFrame:
    """
    Draws a random sample with replacement from the complete global pool of fatalities data from the year before.
    """
    
    if target == "pgm":
        unit = "priogrid_gid"
    elif target == "cm":
        unit = "country_id"
    else:
        raise ValueError('Target must be "pgm" or "cm.')


    filter = pac.field("year") == year - 1
    pool = pq.ParquetDataset(feature_folder / target, filters = filter).read(columns = ["ged_sb"]).to_pandas()

    filter = pac.field("year") == year
    df = pq.ParquetDataset(feature_folder / target, filters = filter).read(columns = [unit, "month_id"]).to_pandas()

    df["outcome"] = np.random.choice(pool["ged_sb"], size = (df.shape[0], 1000), replace = True).tolist()
    df = df.explode('outcome').astype('int32')
    df['draw'] = df.groupby(['month_id', unit]).cumcount()
    return df



feature_folder = Path("path/to/features")
targets = ["pgm", "cm"]
years = range(2018, 2022)
for target in targets:
    for year in years:
        global_bootstrap_benchmark(feature_folder, target, year)
```

2023-10-17 09:10 UTC, kvelleby commented on bootstrap_.py
Some of the things you have written here (like parsing month_id's) etc, I have put in the utilities.py module

2023-10-17 09:10 UTC, kvelleby commented on bootstrap_.py
Great that you add a command-line interface. If you rename the module to "benchmarks.py", then the main() should have an argument for the kind of benchmark to run, and the path to the feature_folder. The rest of the arguments should have sensible defaults (like selecting both cm and pgm level, and iterating over relevant years).

2023-10-17 09:55 UTC, kvelleby commented on bootstrap_.py
Also note: 
```
import pyarrow.compute as pac
import pyarrow.parquet as pq
```

2023-10-24 09:36 UTC, closed without merging